name: PhantomReplay
version: '${version}'

main: de.affenherzog.phantomReplay.PhantomReplay
api-version: '1.21.11'
load: POSTWORLD

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true

loader: de.affenherzog.phantomReplay.PhantomReplayLoader