CREATE TABLE IF NOT EXISTS player
(
    uuid VARCHAR(36) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS replay
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    name       VARCHAR(255) NOT NULL,
    data       LONGBLOB     NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (uuid) REFERENCES player (uuid) ON DELETE CASCADE
);